/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 payphoneGray.glb -T -t s -i 
Files: payphoneGray.glb [4.38MB] > payphoneGray-transformed.glb [97.63KB] (98%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import payphoneGaryPath from "./payphoneGray.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    uploads_files_3109365_1025: THREE.Mesh;
    uploads_files_3109365_1025_1: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
  };
};

type PayphoneProps = {
  onPayphoneClick?: () => void;
} & JSX.IntrinsicElements["group"];

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function PayphoneGray({
  onPayphoneClick,
  ...props
}: PayphoneProps) {
  const { nodes, materials } = useGLTF(payphoneGaryPath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.269, 5.541, -1.713]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.47}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_3109365_1025.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_3109365_1025_1.geometry}
          material={nodes.uploads_files_3109365_1025_1.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(payphoneGaryPath);
