/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 payphone.glb -T -t s -i 
Files: payphone.glb [4.52MB] > payphone-transformed.glb [97.82KB] (98%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import payphonePath from "./payphone.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    uploads_files_3109365_1011: THREE.Mesh;
    uploads_files_3109365_1024: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
  };
};

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
// >;

export default function Payphone(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(payphonePath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.uploads_files_3109365_1011.geometry}
        material={materials.PaletteMaterial001}
        position={[0.269, 5.541, -1.713]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.uploads_files_3109365_1024.geometry}
        material={nodes.uploads_files_3109365_1024.material}
        position={[0.269, 5.541, -1.713]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

// useGLTF.preload("/payphone-transformed.glb");
